### ISSUE TITLE
Plugin not work when using with development server

### ISSUE THREAD

**Issue by Gu-Miao** [sapphi-red/vite-plugin-static-copy#10]
Version: 0.4.2

My config:
```
// vite.config.ts
export default defineConfig({
  plugins: [
    vue(),
    copy({
      targets: [
        {
          src: [
            'node_modules/cesium/Build/Cesium/Assets',
            'node_modules/cesium/Build/Cesium/ThirdParty',
            'node_modules/cesium/Build/Cesium/Widgets',
            'node_modules/cesium/Build/Cesium/Workers'
          ],
          dest: '/'
        }
      ]
    })
  ],
  // Some more...
})
```

`Assets`, `ThirdParty`, `Widgets` and `Workers` are all directories. It worked fun when runing build script. But when I use with `npm run dev`, I got a lot of 404.

I find that I can let it work if I fallback to version 0.2.

**Comment by sapphi-red** [comment]
@Gu-Miao I have released a fix for this (v0.4.3). Does it work for you?

**Comment by Gu-Miao** [comment]
Thanks for that quick fix!! Let me try it.

**Comment by Gu-Miao** [comment]
I think the problem is ok now. Thanks again!
