### ISSUE TITLE
"vite-plugin-static-copy" resolved to an ESM file

### ISSUE THREAD

**Issue by lydemann** [sapphi-red/vite-plugin-static-copy#104]
When I run with a non mjs config I get:

ERROR: [plugin: externalize-deps] "vite-plugin-static-copy" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.

Should the plugin also support CJS?

**Comment by Ken-vdE** [comment]
Adding `"type":"module",` to my package.json file fixed this issue.
