### ISSUE TITLE
Consider normalizing paths by default

### ISSUE THREAD

**Issue by wojtekmaj** [sapphi-red/vite-plugin-static-copy#112]
A good chunk of README is about Windows support and how normalizePath needs to be used, "or else". Since my projects are regularly ran on multiple OSes, I use normalizePath in my configuration files and it seems to work just fine _both_ on Windows and macOS. So why all this hassle? Is there any good reason for paths _not_ to be normalized by default, allowing cross-OS configuration much more dev friendly?

**Comment by sapphi-red** [comment]
It's because the plugin doesn't know if `\` means `/` (path separator) or `\` (escape character).
https://github.com/micromatch/micromatch#backslashes:~:text=In%20other%20words,more%20serious%2C%20problem
If the plugin converts it automatically, users won't be able to escape characters.
