### ISSUE TITLE
Set content-type header from target filename

### ISSUE THREAD

**Issue by tobz1000** [sapphi-red/vite-plugin-static-copy#119]
I use the transform function to convert SVGs to PNGs, and to generate json metadata files from script files. When these transformed files are served, the `content-type` header in the response is for SVG and `.ts` files (which are interpreted as `video/mp2t`).

It would be better if the target filename was used on renamed files when determining the content-type to use. Or alternatively, an option to set this header manually.

**Comment by sapphi-red** [comment]
> It would be better if the target filename was used on renamed files when determining the content-type to use.

That makes sense. PR is welcome.
