### ISSUE TITLE
[difference] 1.x 0.x They have different effects

### ISSUE THREAD

**Issue by tyouzu1** [sapphi-red/vite-plugin-static-copy#120]
when i use @vitejs/plugin-legacy，They triggered different times，1.x lost one trigger

0.x

![image](https://github.com/sapphi-red/vite-plugin-static-copy/assets/26712711/79e87dc5-47d2-4a8f-ae20-d91eb780fffc)

1.x
![image](https://github.com/sapphi-red/vite-plugin-static-copy/assets/26712711/d0d91fc1-fe68-4553-9c59-3bc604bc5852)

**Comment by sapphi-red** [comment]
This is an expected change: https://github.com/sapphi-red/vite-plugin-static-copy/pull/67
This plugin expects all the files to be copied to exist before the build starts.
