### ISSUE TITLE
Support vitev4.5.3

### ISSUE THREAD

**Issue by swotiendang** [sapphi-red/vite-plugin-static-copy#124]
I install the plugin with but face issue
> npm i vite-plugin-static-copy

![image](https://github.com/sapphi-red/vite-plugin-static-copy/assets/147467559/9a8e1e1e-4e27-4890-b106-6f95e65cc72f)

I request the lib document to specify which version support vite@4.5.1

**Comment by sapphi-red** [comment]
I won't support Vite 4.x in 1.x+. You can use v0.17.1 for Vite 4.
But I'll suggest upgrading Vite to v5.x. More than half a year has passed since the release.
