### ISSUE TITLE
[suggestion] throws an error when it doesn't find the file/path

### ISSUE THREAD

**Issue by tassioFront** [sapphi-red/vite-plugin-static-copy#126]
# [suggestion] throws an error when it doesn't find the file

I have been using the vite-plugin-static-copy for a while and recently I needed to move the file path it copies. So, I changed the copied file from `src/old-path` to `src/new-path`, but I forgot to update the plugin configuration:

 ```TS
   viteStaticCopy({
      targets: [
        {
          src: './src/old-path.js', // I must update this line, but even without doing it the build keeps working.
          //...more config
        },
      ],
    }),
```
Unfortunately, it does not throw any error, so I noticed it fails after manual validations. Does make sense to throw an error when the plugin doesn't find the file?

**Comment by sapphi-red** [comment]
I think we can have a warning log in build.

**Comment by tassioFront** [comment]
To be honest, I think it should fail once the application won't work as expected, but a warning would help a lot. :raised_hands:

**Comment by tassioFront** [comment]
@sapphi-red, I was creating the PR when I saw this on my terminal: 
![Screenshot from 2024-09-13 15-14-52](https://github.com/user-attachments/assets/cddfa291-93e0-4d59-902e-9c636704b546)

This validation is done [here](https://github.com/sapphi-red/vite-plugin-static-copy/blob/2ac7070d3cc5d38f03fb7fde0dde0fc69cc606ac/src/utils.ts#L248)

Guess it proves the warning is not enough. :sweat_smile:  Anyway, let me know if makes sense to open the PR, or I can change the warning message like:

`'No file was found to copy on ${src} src.'`

**Comment by tassioFront** [comment]
@sapphi-red what do you think?

**Comment by sapphi-red** [comment]
Hmmm, yeah, probably an error is better.
But I think throwing an error will break usecases like slidev (https://github.com/sapphi-red/vite-plugin-static-copy/pull/52).

So I think we need to cut a major version and also add an option to ignore the error.

**Comment by tassioFront** [comment]
@sapphi-red perfect!

Let me know what you think about [this changes](https://github.com/sapphi-red/vite-plugin-static-copy/pull/127/files).

**Comment by vedranstipancic** [comment]
This seriously hindered the way we use the plugin.
We have a common vite config for several projects. It includes some things to copy which are optional on projects. Until now it wasn't an issue, because it just didn't copy things it didn't find.
Now it
- breaks my build if nothing found
- if I turn on silent  absolutely nothing gets copied, because one of the copies failed
- if I break up one copy into several copies, it doesn't work  during development

**Comment by tassioFront** [comment]
@vedranstipancic, which version were you using before it started, and which one now?
