### ISSUE TITLE
Type plugin isnt assignable to type PluginOptions

### ISSUE THREAD

**Issue by bearcattt** [sapphi-red/vite-plugin-static-copy#144]
I updated to vite ^6.0.2 and vite-plugin-static-copy to latest. I tried building it and the errors below came. 
`[{
	"resource": "/workspaces/dev-lunar/astro.config.ts",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type 'Plugin<any>[]' is not assignable to type 'PluginOption'.\n  Type 'Plugin<any>[]' is not assignable to type 'PluginOption[]'.\n    Type 'Plugin<any>' is not assignable to type 'PluginOption'.\n      Type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").Plugin<any>' is not assignable to type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").Plugin<any>'.\n        Types of property 'apply' are incompatible.\n          Type '\"serve\" | \"build\" | ((this: void, config: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").UserConfig, env: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@...' is not assignable to type '\"serve\" | \"build\" | ((this: void, config: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").UserConfig, env: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").ConfigEnv) => boolean) |...'.\n            Type '(this: void, config: UserConfig, env: ConfigEnv) => boolean' is not assignable to type '\"serve\" | \"build\" | ((this: void, config: UserConfig, env: ConfigEnv) => boolean) | undefined'.\n              Type '(this: void, config: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").UserConfig, env: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vi...' is not assignable to type '(this: void, config: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").UserConfig, env: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").ConfigEnv) => boolean'.\n                Types of parameters 'config' and 'config' are incompatible.\n                  Type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").UserConfig' is not assignable to type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").UserConfig'.\n                    Types of property 'plugins' are incompatible.\n                      Type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").PluginOption[] | undefined' is not assignable to type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").PluginOption[] | undefined'.\n                        Type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").PluginOption[]' is not assignable to type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").PluginOption[]'.\n                          Type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").PluginOption' is not assignable to type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").PluginOption'.\n                            Type 'Plugin<any>' is not assignable to type 'PluginOption'.\n                              Type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").Plugin<any>' is not assignable to type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").Plugin<any>'.\n                                Types of property 'apply' are incompatible.\n                                  Type '\"serve\" | \"build\" | ((this: void, config: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").UserConfig, env: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").ConfigEnv) => boolean) |...' is not assignable to type '\"serve\" | \"build\" | ((this: void, config: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").UserConfig, env: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@...'.\n                                    Type '(this: void, config: UserConfig, env: ConfigEnv) => boolean' is not assignable to type '\"serve\" | \"build\" | ((this: void, config: UserConfig, env: ConfigEnv) => boolean) | undefined'.\n                                      Type '(this: void, config: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").UserConfig, env: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").ConfigEnv) => boolean' is not assignable to type '(this: void, config: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").UserConfig, env: import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vi...'.\n                                        Types of parameters 'config' and 'config' are incompatible.\n                                          Type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").UserConfig' is not assignable to type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").UserConfig'.\n                                            Types of property 'plugins' are incompatible.\n                                              Type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").PluginOption[] | undefined' is not assignable to type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").PluginOption[] | undefined'.\n                                                Type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").PluginOption[]' is not assignable to type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").PluginOption[]'.\n                                                  Type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@1.21.6_tsx@4.19.2_yaml@2.6.0/node_modules/vite/dist/node/index\").PluginOption' is not assignable to type 'import(\"/workspaces/dev-lunar/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1/node_modules/vite/dist/node/index\").PluginOption'.\n                                                    Type 'Promise<Plugin<any> | FalsyPlugin | PluginOption[]>' is not assignable to type 'PluginOption'.\n                                                      Type 'Promise<Plugin<any> | FalsyPlugin | PluginOption[]>' is not assignable to type 'Promise<false | Plugin<any> | PluginOption[] | null | undefined>'.\n                                                        Type 'Plugin<any> | FalsyPlugin | PluginOption[]' is not assignable to type 'false | Plugin<any> | PluginOption[] | null | undefined'.\n                                                          Type 'Plugin<any>' is not assignable to type 'false | Plugin<any> | PluginOption[] | null | undefined'.",
	"source": "ts",
	"startLineNumber": 56,
	"startColumn": 7,
	"endLineNumber": 74,
	"endColumn": 9
}]`

**Comment by sapphi-red** [comment]
It seems you have `vite@5.4.11` installed together with `vite@6.0.2`. Probably upgrading the transitive dependencies would solve the error.

**Comment by bearcattt** [comment]
Thank you
