### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by elite174** [sapphi-red/vite-plugin-static-copy#15]
It doesn't work for windows

**Comment by sapphi-red** [comment]
CI is running for linux and windows so it should work. Also it is working on my windows PC.
Please provide a reproduction.

**Comment by sapphi-red** [comment]
Thanks @wkl007.

@elite174 
As @wkl007 said, you need to use `normalizePath`. `\\` means escape for fast-glob.

**Comment by elite174** [comment]
Thank you so much!

**Comment by wkl007** [comment]
You are welcome @sapphi-red

**Comment by elite174** [comment]
I tried path normalization and it doesn't work.
Seems that it doesn't work with symllinks on windows correctly, because I tried the same code under wsl and everything works as expected.

In my project I use rush monorepo manager with pnpm

**Comment by sapphi-red** [comment]
Would you create a new issue with reproduction?
