### ISSUE TITLE
Add optional src watcher

### ISSUE THREAD

**Issue by gauravjhs** [sapphi-red/vite-plugin-static-copy#3]
Hey... many thanks for this awesome plugin. What's the best way to add file or dir watcher for any changes in the src dir?

**Comment by sapphi-red** [comment]
Currently there is no way to do that.

**Comment by sapphi-red** [comment]
@gauravjhs Implemented with version 0.3.0.

**Comment by gauravjhs** [comment]
thanks @sapphi-red. This should be very helpful for the community.
