### ISSUE TITLE
During dev, the plugin could not serve the files with no suffix

### ISSUE THREAD

**Issue by jianwenjuan** [sapphi-red/vite-plugin-static-copy#32]
I am using this plugin in my Vite project to copy the public files during dev, the files with no extension could not be served.
![image](https://user-images.githubusercontent.com/22387830/197672254-33f9a810-6d8d-4297-bb9f-149f54750f0a.png)

**Comment by sapphi-red** [comment]
I have released a fix for this (v0.11.0).

**Comment by jianwenjuan** [comment]
> I have released a fix for this (v0.11.0).

It works for me now~ thank you very much, you are my lifesaver.
