### ISSUE TITLE
[Windows] EPERM: operation not permitted, symlink

### ISSUE THREAD

**Issue by kingyue737** [sapphi-red/vite-plugin-static-copy#34]
OS: Windows 11

In dev mode, it works perfectly, but when I try to build, the following error exists:
```
Error: EPERM: operation not permitted, symlink 'D:\Solutions\my-repo\node_modules\.pnpm\shiki@0.11.1\node_modules\shiki' -> 'D:\Solutions\my-repo\dist\shiki'
```

Any help would be appreciated!

**Comment by sapphi-red** [comment]
I guess it's failing because Windows requires administrator permission to create a symlink by default.
Maybe it will work if `dereference: true` was passed here.
https://github.com/sapphi-red/vite-plugin-static-copy/blob/f355fe1c472e1637110497fe6922f4b055bc48ef/src/utils.ts#L121

**Comment by kingyue737** [comment]
Directly copying file to `dist` rather than symlink make the `dist` folder portable (I can easily send all files to others). Maybe add an option to allow user to determine whether copy or symlink?
