### ISSUE TITLE
Support for optional file watching

### ISSUE THREAD

**Issue by sashabaranova** [sapphi-red/vite-plugin-static-copy#35]
Hi there! I recently integrated the plugin in my project and it perfectly fit my needs. However, I ran into an issue with file watching in CI/CD - with chokadir running it hits the limit of fs watchers. Given that file watching in CI/CD is not required, maybe it would be a good idea to make file watching optional?

**Comment by sapphi-red** [comment]
This plugin uses chokidar only for dev. Because Vite uses chokidar for dev and there isn't a way to disable that, I think you need an option in Vite first.

**Comment by sapphi-red** [comment]
Closing due to lack of response.
