### ISSUE TITLE
Files are found, but not copied

### ISSUE THREAD

**Issue by FluffyDiscord** [sapphi-red/vite-plugin-static-copy#53]
I can see in the console output that files are found, but I cannot see them being copied anywhere.

Project tree:
- assets/images/
- assets/images/folder1/image.jpg
- assets/images/folder2/file.pdf
- public/build/manifest.json (generated by Vite)

I am trying to copy everything including the folder structure from `assets/images` to `public/build/images`, so for example the `assets/images/folder1/image.jpg` would end up at `public/build/images/folder1/image.jpg`

`vite.config.js`
```js
export default defineConfig({
    plugins: [
        viteStaticCopy({
            targets: [
                {
                    src: path.resolve(__dirname, "assets/images/**/*"),
                    dest: "images",
                },
            ],
            watch: {
                reloadPageOnChange: true,
            },
            flatten: false,
        }),
    ],
})
```

The console shows that it found bunch of files, but nothing is being copied anywhere, or at least not inside the project folder.
![image](https://user-images.githubusercontent.com/10332247/235900064-9f282fcc-724c-4fcc-9e8f-0e78926b3e4f.png)

**Comment by sapphi-red** [comment]
This behavior is expected. See #29
