### ISSUE TITLE
Add support for Vite 5

### ISSUE THREAD

**Issue by wojtekmaj** [sapphi-red/vite-plugin-static-copy#64]
Currently, instaling vite-plugin-static-copy along with Vite 5 results in:

```
➤ YN0060: │ vite is listed by your project with version 5.0.0, which doesn't satisfy what vite-plugin-static-copy requests (^3.0.0 || ^4.0.0).
```

According to my tests, it looks like updating it is gonna be as easy as updating the list of peerDependencies.

**Comment by sapphi-red** [comment]
I released 0.17.1 that bumps the peerDep 👍
