### ISSUE TITLE
The entire module stopped working

### ISSUE THREAD

**Issue by wuhaohuang** [sapphi-red/vite-plugin-static-copy#74]
hi~
I made this update progress:
Bump vite-plugin-static-copy from 0.17.0 to 1.0.0 and vite from 4.3.9 to 5.0.10.

Now the module no longer loads on Vite in any way:
```
✘ [ERROR] "vite-plugin-static-copy" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]
```
<img width="1546" alt="image" src="https://github.com/sapphi-red/vite-plugin-static-copy/assets/19322584/39f85ed4-609f-43c8-ad43-b1a923b4b1a2">

When I downgraded, everything went back to normal. So the problem is in the version 1.0.0
Or I renamed the file vite.config.js to vite.config.mjs and this is working now.

Your module was using the file name as a reference to know if it was an ESM or not. pls check and good luck.

**Comment by wuhaohuang** [comment]
replenish: my current naming is vite.config.ts, is not working

**Comment by SirNiklax** [comment]
I have this issue too when using vite.config.ts but vite.config.mts works although the package is a [module](https://vitejs.dev/guide/migration#:~:text=has%20%22type%22%3A-,%22module%22,-%2C%20or%20use%20the).

**Comment by sapphi-red** [comment]
Please read the error message and the linked page.

> "vite-plugin-static-copy" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
