### ISSUE TITLE
Using structured:true generates wrong path

### ISSUE THREAD

**Issue by Rusl10** [sapphi-red/vite-plugin-static-copy#78]
Hi. Consider we have the following code
```
// vite.config.mts
export default mergeConfig(baseConfig, {
  ...,
  plugins: [
    viteStaticCopy({
      targets: [
        {
          src: normalizePath(path.resolve(process.cwd(), 'polymer-bundles/calendar/es6-bundled/**')),
          dest: 'polymer-bundles/calendar',
        }
      ],
      structured: true,
    })
  ],
});
```
I have to make the following changes to copy my files correctly 

```
// node_modules/vite-plugin-static-copy/dist/index.js
// const dirClean = dir.replace(/^(?:\.\.\/)+/, "");
const dirClean = dir.replace(/^(?:\.\.\/)+/, "").replace("/home/admin/Desktop/projects/mln/polymer-bundles/calendar/es6-bundled", "");
const destClean = `${dest}/${dirClean}`.replace(/^\/+|\/+$/g, "");
destDir = destClean;
```
By default I get wrong path in destClean variable: `/home/admin/Desktop/projects/mln/dist/apps/web/app/shell/polymer-bundles/calendar/home/admin/Desktop/projects/mln/polymer-bundles/calendar/es6-bundled`
Could you fix this please?
P.S. I use vite with nx. OS ubuntu.

**Comment by sapphi-red** [comment]
There was a bug (#79) related to that but you can use `rename` option to do that.

**Comment by Rusl10** [comment]
![Screenshot from 2024-01-25 09-36-22](https://github.com/sapphi-red/vite-plugin-static-copy/assets/26712091/8ea9c3c9-ca38-4432-81f5-1962a6fe07bb)
I can`t download last version

**Comment by Rusl10** [comment]
@sapphi-red The problem is still exist and now i have to apply the following changes to copy the files correctly
```
// const destClean = `${dest}/${dirClean}`.replace(/^\/+|\/+$/g, "");
const destClean = `${dest}${dirClean.replace("polymer-bundles/calendar/es6-bundled", "")}`.replace(/^\/+|\/+$/g, "");
```
If i start preview server everything works fine, but it does not work for a dev server.  Could you help to solve it please ?

**Comment by Rusl10** [comment]
> There was a bug (#79) related to that but you can use `rename` option to do that.

Can you clarify how should i use this option to solve the bug?

**Comment by sapphi-red** [comment]
I need a reproduction for that.
