### ISSUE TITLE
The 1.0.1 version `rename` update

### ISSUE THREAD

**Issue by orangecoloured** [sapphi-red/vite-plugin-static-copy#83]
I noticed that with the latest update the `rename` function gets the `fullPath`, the third argument, as an absolute system path now, as opposed to the project relative path.
So `/Users/username/long/path/to/project/folder/file/path` instead of `folder/file/path`;

Should there be a way to control this?
It's kind of a breaking change.

**Comment by sapphi-red** [comment]
The parameter name is `fullPath` and I expect it to be a absolute path. Returning a relative path was a bug. In addition, it only did that in some cases.)
https://github.com/sapphi-red/vite-plugin-static-copy/blob/69544bd14f50a150591b89da1c92f3e6f89f8c48/src/options.ts#L5-L9

At this stage, I'm not thinking to add an option to revert to the previous behavior.

**Comment by orangecoloured** [comment]
Alright, `fullPath` makes sense. I'll adapt my code.
It would be great to add a note to the changelog. My build broke because of this.
