### ISSUE TITLE
"vite-plugin-static-copy" resolved to an ESM file

### ISSUE THREAD

**Issue by captDaylight** [sapphi-red/vite-plugin-static-copy#84]
I'm doing something like this in my vite config:

``` js
import { viteStaticCopy } from 'vite-plugin-static-copy';

export default defineConfig({
  plugins: [
    solidPlugin(),
    viteStaticCopy({
      targets: [
         {
           src: resolvePath('/assets'),
           dest: resolvePath('dist')
         }
      ]
```
But receiving the error:
```
"vite-plugin-static-copy" resolved to an ESM file. ESM file cannot be loaded by `require`. 
See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]
```

This is confusing because I'm importing `viteStaticCopy`.

**Comment by captDaylight** [comment]
The answer ended up being that I needed to rename my file from `vite.config.ts` to `vite.config.mts` according to the link they provided: https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only

**Comment by johannesjo** [comment]
Thanks for sharing! Still think this should be resolved without having to change the extension of the config file.

**Comment by PythonCircuit** [comment]
> Thanks for sharing! Still think this should be resolved without having to change the extension of the config file.

Yeah and it makes no sense we have to do this. What combination of my tsconfig target/module/libs and module resolutions do I need to not be confused anymore?

**Comment by thestephenmarshall** [comment]
This is kind of nonsensical having to rename my `vite.config.ts` as it is a breaking change. Why was this issue closed exactly?
