### ISSUE TITLE
Documentation: Some words on what "good uses" for this package are would be welcome

### ISSUE THREAD

**Issue by hybridherbst** [sapphi-red/vite-plugin-static-copy#86]
The readme currently notes:
> Before you use this plugin, consider using [public directory](https://vitejs.dev/guide/assets.html#the-public-directory) or [import in JavaScript](https://vitejs.dev/guide/features.html#static-assets). In most cases, these will work.

However, I keep coming back to this plugin because of the glob and dynamic import limitations in vite, so I thought I'd ask here if that is actually an expected usecase, and potentially some notes on that can go into the readme.

Consider an example structure for a photo albums project, and some photos have a story markdown file.  
The photo album is on a specific location on disk, unrelated to the vite project (using sveltekit here, but shouldn't matter for the question). There are some topics and subtopics where photos are categorized in.  
It is not viable nor desired to just copy the entire set of photo albums into the `public` directory.  

```
- someDirectoryOnDisk
  - topic1
    - photo1.png
    - story1.md
    - photo2.png
    - subtopic
      - photo3.png
      - story3.md
  - topic2
    - photo3.png
    - story4.md
```

Somewhere else on disk, we have a svelte project: 
```
- someDevDirectory
  - package.json
  - vite.config.ts
  - src/routes
    - +page.server.ts
    - +page.svelte
```

**Would you say that is a typical usecase for vite-plugin-static-copy?**  

The flow would be:
- make a utility method that collects absolute paths and desired relative paths for all items
- invoke that from `vite.config.ts` and use `vite-plugin-static-copy` to ensure the files end up in the build
- invoke it also from `+page.server.ts` to pass all the relative paths to `+page.svelte`

It feels "glued together" compared to letting vite handle all imports and file copying, but I can't figure out if/how that would work given the limitations of `import.meta.glob` and dynamic `import` with a single variable. Letting vite handle it would also allow using image optimizations etc., that seem harder to add this way.

**Comment by sapphi-red** [comment]
I'd recommend using symlinks in that case. For example, linking `someDirectoryOnDisk` to `someDevDirectory/src/albums` will let you use `import.meta.glob`.

**Comment by hybridherbst** [comment]
I see. So I would

- symlink the directory
- use import.meta.glob (with eager and raw?) from +page.server.ts or +layout.server.ts and return the data there
- pass the URLs (?) to +page.svelte

Does that sound right?

**Comment by sapphi-red** [comment]
I guess that would work.

**Comment by sapphi-red** [comment]
I'll close this for now as I don't know how to clarify it.
